/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import java.awt.Color;
import java.io.File;

/**
 *
 * @author RYZEN
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreIcon = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        telIcon = new javax.swing.JLabel();
        cajaTelefono = new javax.swing.JTextField();
        correoIcon = new javax.swing.JLabel();
        cajaCorreo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        botonGuardarContac = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mostrarContactos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGENDA DE CONTACTOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, 47));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 700, -1));

        nombreIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/per.png"))); // NOI18N
        jPanel2.add(nombreIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 146, -1, 45));

        cajaNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cajaNombre.setForeground(new java.awt.Color(204, 204, 204));
        cajaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombre.setText("Nombre");
        cajaNombre.setBorder(null);
        cajaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaNombreMousePressed(evt);
            }
        });
        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });
        jPanel2.add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 146, 380, 40));

        telIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/telefono.png"))); // NOI18N
        jPanel2.add(telIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 210, 20, 45));

        cajaTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cajaTelefono.setForeground(new java.awt.Color(204, 204, 204));
        cajaTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTelefono.setText("Teléfono");
        cajaTelefono.setBorder(null);
        cajaTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaTelefonoMousePressed(evt);
            }
        });
        cajaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(cajaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 380, 40));

        correoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo-electronico.png"))); // NOI18N
        jPanel2.add(correoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, 45));

        cajaCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cajaCorreo.setForeground(new java.awt.Color(204, 204, 204));
        cajaCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCorreo.setText("Email");
        cajaCorreo.setBorder(null);
        cajaCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaCorreoMousePressed(evt);
            }
        });
        cajaCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(cajaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 380, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 380, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 370, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 380, 50));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 380, 60));

        botonGuardarContac.setBackground(new java.awt.Color(0, 102, 102));
        botonGuardarContac.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarContac.setText("Guardar");
        botonGuardarContac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarContacMouseClicked(evt);
            }
        });
        botonGuardarContac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarContacActionPerformed(evt);
            }
        });
        jPanel2.add(botonGuardarContac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 150, 40));

        barraMenu.setBackground(new java.awt.Color(255, 255, 255));

        menu.setForeground(new java.awt.Color(0, 0, 0));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        menu.setText("Menú");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N

        mostrarContactos.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        mostrarContactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contactos.png"))); // NOI18N
        mostrarContactos.setText("Mostrar Contactos");
        mostrarContactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContactosActionPerformed(evt);
            }
        });
        menu.add(mostrarContactos);
        menu.add(jSeparator1);

        salir.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        salir.setText("Salir");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        menu.add(salir);

        barraMenu.add(menu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContactosActionPerformed
        ventanaContactos VentanaC = new ventanaContactos(this, true);
        VentanaC.setVisible(true);
    }//GEN-LAST:event_mostrarContactosActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void cajaCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCorreoActionPerformed

    private void cajaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTelefonoActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
       
    }//GEN-LAST:event_jPanel2MouseEntered

    private void cajaNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaNombreMousePressed
        if (cajaNombre.getText().equals("Nombre")){
            cajaNombre.setText("");
            cajaNombre.setForeground(Color.black);
        }
        if(cajaTelefono.getText().isEmpty()){
             cajaTelefono.setText("Teléfono");
        }
      if(cajaCorreo.getText().isEmpty()){
          cajaCorreo.setText("Email");
      }
       
      
    }//GEN-LAST:event_cajaNombreMousePressed

    private void cajaTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaTelefonoMousePressed
     
          
      if (cajaTelefono.getText().equals("Teléfono")){
          cajaTelefono.setText("");
          cajaTelefono.setForeground(Color.black);
      }
       if(cajaNombre.getText().isEmpty()){
           cajaNombre.setText("Nombre");
       } 
          if(cajaCorreo.getText().isEmpty()){
              cajaCorreo.setText("Email");
          }
        
       
       
       
    }//GEN-LAST:event_cajaTelefonoMousePressed

    private void cajaCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaCorreoMousePressed
      if (cajaCorreo.getText().equals("Email")){
          cajaCorreo.setText("");
       cajaCorreo.setForeground(Color.black);
      }
      if(cajaNombre.getText().isEmpty()){
           cajaNombre.setText("Nombre");
          
      }
       
        if(cajaTelefono.getText().isEmpty()){
            cajaTelefono.setText("Teléfono");
            
        }
       
       
    }//GEN-LAST:event_cajaCorreoMousePressed

    private void botonGuardarContacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarContacActionPerformed
        Archivo archivo = new Archivo();
        archivo.crearArchivo();
        
        String nombre,telefono,correo;
        //se obtienen los datos de las cajas de texto
        nombre = cajaNombre.getText();
        telefono = cajaTelefono.getText();
        correo =cajaCorreo.getText();
        
        //creamos un objeto persona
        Persona persona = new Persona(nombre, correo, telefono);
        
        archivo.escribirTexto(persona);
        cajaNombre.setText("");
        cajaTelefono.setText("");
        cajaCorreo.setText("");
        
        
        
        
        
    }//GEN-LAST:event_botonGuardarContacActionPerformed

    private void botonGuardarContacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarContacMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this,"Contacto Guardado" );
    }//GEN-LAST:event_botonGuardarContacMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonGuardarContac;
    private javax.swing.JTextField cajaCorreo;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaTelefono;
    private javax.swing.JLabel correoIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem mostrarContactos;
    private javax.swing.JLabel nombreIcon;
    private javax.swing.JMenuItem salir;
    private javax.swing.JLabel telIcon;
    // End of variables declaration//GEN-END:variables

    private void setLocationtRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
